services:
  nginx:
    image: nginx:1.29.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cdn-network
    depends_on:
      - frontend
      - backend

  frontend:
    build: web
    networks:
      - cdn-network
    depends_on:
      - backend

  backend:
    build: rest-server
    hostname: backend
    restart: on-failure
    networks:
      - cdn-network
    environment:
      RUST_LOG: INFO
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    networks:
      - cdn-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  localstack_data: {}
networks:
  cdn-network: {}
