services:
  frontend:
    build: web
    ports:
      - "8080:3001"
    networks:
      - cdn-network
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - API_ENDPOINT=http://localhost:4566/restapis/default

  localstack:
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./lambda:/etc/localstack/init/ready.d/lambda"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - cdn-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  localstack_data: {}
networks:
  cdn-network: {}
