services:
  nginx:
    image: nginx:1.29.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cdn-network
    depends_on:
      - backend

  backend:
    build: .
    hostname: backend
    restart: on-failure
    networks:
      - cdn-network
    volumes:
      - ./uploads:/var/cdn/storage
    environment:
      POSTGRES_DB: cdn
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RUST_LOG: TRACE
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.18
    restart: on-failure
    environment:
      POSTGRES_DB: cdn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cdn-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: { }
networks:
  cdn-network: { }